---

name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.12.2'

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-
          path: |
            _build
            deps
            priv/plts

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Tests
        run: mix test
        env:
          DB_HOST: postgres

  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.12.2'

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Formatter
        run: mix format --check-formatted

  Dialyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.12.2'

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-
          path: |
            _build
            deps
            priv/plts

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Dialyzer
        run: mix dialyzer

  Credo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.12.2'

      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-
          path: |
            _build
            deps
            priv/plts

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Credo
        run: mix credo
